# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160622_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=b'SOME STRING', unique=True),
        ),
    ]
