# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160622_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name=b'slug'),
        ),
    ]
