# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160623_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
